### PR TITLE
Return latest positions list for each vehicle 

### PR DESCRIPTION
**Pull request by adnen-chouibi**
use method post instead of push

### CODE REVIEW

**Comment by adnen-chouibi** [comment]
The body params should  be enclosed by double quote

**Comment by AlainH** [comment]
The body of the request should be a JSON array of asset ids:
[ 12345678912345, 543210987654321 ]

**Comment by Archana-g-s** [comment]
> The body of the request should be a JSON array of asset ids:
> [ 12345678912345, 543210987654321 ]

Hi Alain,  This returns a 500  internal server error.  Is there another way i can try ?  Appreciate your help. 

Request: https://integrate.au.mixtelematics.com/api/positions/assets/latest/1
JSON -> [12345678912345, 543210987654321 ]
500 Internal Server Error

**Comment by AlainH** [comment]
When using Python's requests library, you can pass data using the  **json** parameter instead of the **data** parameter.  This automatically serializes the passed-in data to JSON for you and sets the appropriate headers on the request:

idList = [1234567890123456789, -9876543210987654321]
url= "https://integrate.au.mixtelematics.com/api/positions/assets/latest/1"
response = requests.post(url, json = idList, headers = {"Authorization":BearerToken})

**Pull request closed without merging**
